/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.95
 * Generated at: 2025-02-16 07:56:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.pages.cms;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class cmsprofile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/WEB-INF/pages/common/styles.jspf", Long.valueOf(1739170343480L));
    _jspx_dependants.put("/WEB-INF/pages/common/head.jspf", Long.valueOf(1739170343480L));
    _jspx_dependants.put("/WEB-INF/pages/common/footer.jspf", Long.valueOf(1739170343480L));
    _jspx_dependants.put("/WEB-INF/pages/common/footerscripts.jspf", Long.valueOf(1739170343480L));
    _jspx_dependants.put("/WEB-INF/pages/common/navbarsidebarlogin.jspf", Long.valueOf(1739178670492L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("    ");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../../../resources/styles/styles.css\">\r\n");
      out.write("<link rel=\"icon\" href=\"#\" type=\"image/gif\">\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\" \r\n");
      out.write("      rel=\"stylesheet\" integrity=\"sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH\" \r\n");
      out.write("      crossorigin=\"anonymous\">\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    ");
      out.write("<style>\r\n");
      out.write("    html, body {\r\n");
      out.write("        min-height: 100vh;\r\n");
      out.write("        display: flex;\r\n");
      out.write("        flex-direction: column;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    body {\r\n");
      out.write("        padding-top: 60px;\r\n");
      out.write("        background-color: #f8f9fa; /* Light background */\r\n");
      out.write("        color: #4b0082; /* Dark purple text */\r\n");
      out.write("        font-family: 'Arial', sans-serif;\r\n");
      out.write("        display: flex;\r\n");
      out.write("        flex-direction: column;\r\n");
      out.write("        min-height: 100vh;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .navbar {\r\n");
      out.write("        background-color: #e6e6fa; /* Lavender background for navbar */\r\n");
      out.write("        box-shadow: 0px 4px 10px rgba(0, 0, 0, 0.1);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .navbar-brand, .navbar-nav .nav-link {\r\n");
      out.write("        color: #4b0082 !important; /* Purple text */\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .navbar-brand:hover, .navbar-nav .nav-link:hover {\r\n");
      out.write("        color: #9370db !important; /* Lighter purple on hover */\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .offcanvas-sidebar {\r\n");
      out.write("        width: 20%;\r\n");
      out.write("        background-color: #e6e6fa; /* Lavender background for sidebar */\r\n");
      out.write("        padding: 20px;\r\n");
      out.write("        color: #4b0082; /* Purple text */\r\n");
      out.write("        display: flex;\r\n");
      out.write("        flex-direction: column;\r\n");
      out.write("        justify-content: space-between;\r\n");
      out.write("        height: 100%;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .offcanvas-sidebar .list-group-item {\r\n");
      out.write("        background-color: #f3e5f5; /* Light purple for list items */\r\n");
      out.write("        color: #4b0082; /* Purple text */\r\n");
      out.write("        border: none;\r\n");
      out.write("        padding: 10px 20px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .offcanvas-sidebar .list-group-item.disabled {\r\n");
      out.write("        opacity: 0.6;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .btn-panel button {\r\n");
      out.write("        margin-bottom: 10px;\r\n");
      out.write("        background-color: #9370db; /* Medium purple buttons */\r\n");
      out.write("        color: white;\r\n");
      out.write("        border: none;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .btn-panel button:hover {\r\n");
      out.write("        background-color: #ba55d3; /* Bright purple on hover */\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .login-message {\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        margin-top: 20px;\r\n");
      out.write("        font-size: 1rem;\r\n");
      out.write("        color: #8a2be2; /* Purple warning text */\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .btn-success {\r\n");
      out.write("        background-color: #9370db; /* Medium purple buttons */\r\n");
      out.write("        border-color: #9370db;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .btn-success:hover {\r\n");
      out.write("        background-color: #ba55d3; /* Bright purple on hover */\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .btn-outline-success {\r\n");
      out.write("        color: #4b0082; /* Purple outline buttons */\r\n");
      out.write("        border-color: #4b0082;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .btn-outline-success:hover {\r\n");
      out.write("        color: white;\r\n");
      out.write("        background-color: #9370db; /* Medium purple on hover */\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .container.content {\r\n");
      out.write("        margin-top: 30px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .content {\r\n");
      out.write("        flex: 1;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* Footer styling */\r\n");
      out.write("    .footer {\r\n");
      out.write("        background-color: #e6e6fa; /* Lavender background */\r\n");
      out.write("        color: #4b0082; /* Purple text */\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        padding: 20px 0;\r\n");
      out.write("        margin-top: auto; /* Pushes footer to the bottom */\r\n");
      out.write("        box-shadow: 0 -2px 5px rgba(0, 0, 0, 0.1); /* Subtle shadow for separation */\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .footer p {\r\n");
      out.write("        margin: 0;\r\n");
      out.write("        font-size: 1rem;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* Container for consistent spacing */\r\n");
      out.write("    .container {\r\n");
      out.write("        max-width: 1200px;\r\n");
      out.write("        margin: 0 auto;\r\n");
      out.write("        padding: 0 15px;\r\n");
      out.write("    }\r\n");
      out.write("</style>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <title>Edit Profile</title>\r\n");
      out.write("\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("    <style>\r\n");
      out.write("        /* Ensure navbar style remains unaffected */\r\n");
      out.write("        .navbar {\r\n");
      out.write("            background-color: #e6e6fa; /* Lavender background as per shared styles */\r\n");
      out.write("            box-shadow: 0px 4px 10px rgba(0, 0, 0, 0.1); /* Retain the original shadow */\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .navbar-brand, .navbar-nav .nav-link {\r\n");
      out.write("            color: #4b0082 !important; /* Retain purple text for links */\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .navbar-brand:hover, .navbar-nav .nav-link:hover {\r\n");
      out.write("            color: #9370db !important; /* Lighter purple on hover */\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Styles specific to the profile edit form */\r\n");
      out.write("        .profile-edit-form {\r\n");
      out.write("            max-width: 600px; /* Restrict form width for better readability */\r\n");
      out.write("            margin: 20px auto; /* Center align form */\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("            background-color: #ffffff; /* White background for the form */\r\n");
      out.write("            border: 1px solid #ccc;\r\n");
      out.write("            border-radius: 8px; /* Rounded corners */\r\n");
      out.write("            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1); /* Subtle shadow for the form */\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .profile-edit-form label {\r\n");
      out.write("            font-weight: bold; /* Bold font for labels */\r\n");
      out.write("            display: block; /* Ensure labels occupy a full line */\r\n");
      out.write("            margin-bottom: 5px;\r\n");
      out.write("            color: #4b0082; /* Consistent purple color for form labels */\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .profile-edit-form input,\r\n");
      out.write("        .profile-edit-form textarea,\r\n");
      out.write("        .profile-edit-form button {\r\n");
      out.write("            width: 100%; /* Stretch inputs and buttons across the container */\r\n");
      out.write("            margin: 5px 0 15px 0; /* Add spacing between controls */\r\n");
      out.write("            padding: 10px;\r\n");
      out.write("            border: 1px solid #ccc;\r\n");
      out.write("            border-radius: 5px; /* Rounded inputs */\r\n");
      out.write("            font-size: 1rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .profile-edit-form input[readonly] {\r\n");
      out.write("            background-color: #f8f9fa; /* Slight gray background for readonly inputs */\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .profile-edit-form button {\r\n");
      out.write("            background-color: #9370db; /* Medium purple for buttons */\r\n");
      out.write("            color: white; /* Bright text for visibility */\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            border: none;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .profile-edit-form button:hover {\r\n");
      out.write("            background-color: #ba55d3; /* Lighter purple for hover */\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Style for cancel button */\r\n");
      out.write("        .profile-edit-form button[type=\"button\"] {\r\n");
      out.write("            background-color: transparent; /* Transparent for cancel */\r\n");
      out.write("            color: #4b0082; /* Purple border for cancel button */\r\n");
      out.write("            border: 1px solid #4b0082;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .profile-edit-form button[type=\"button\"]:hover {\r\n");
      out.write("            background-color: #9370db; /* Purple hover */\r\n");
      out.write("            color: white;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Styling for the page heading */\r\n");
      out.write("        .profile-edit-header {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            font-size: 2rem;\r\n");
      out.write("            color: #4b0082; /* Bold purple heading */\r\n");
      out.write("            margin-bottom: 20px;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write('\r');
      out.write('\n');
      out.write("<nav class=\"navbar navbar-expand-lg navbar-dark fixed-top\">\r\n");
      out.write("    <div class=\"container-fluid\">\r\n");
      out.write("        <button class=\"btn btn-secondary\" type=\"button\" data-bs-toggle=\"offcanvas\" data-bs-target=\"#offcanvasSidebar\" aria-controls=\"offcanvasSidebar\">\r\n");
      out.write("            <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("        </button>\r\n");
      out.write("        <a class=\"navbar-brand ms-3\" href=\"/\">EduMentor</a>\r\n");
      out.write("        <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarContent\" aria-controls=\"navbarContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("            <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("        </button>\r\n");
      out.write("        <div class=\"collapse navbar-collapse\" id=\"navbarContent\">\r\n");
      out.write("            <ul class=\"navbar-nav me-auto mb-2 mb-lg-0\">\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link active\" aria-current=\"page\" href=\"discover.html\">Discover</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"about.html\">About Us</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item dropdown\">\r\n");
      out.write("                    <a class=\"nav-link dropdown-toggle\" href=\"#\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("                        Choose the lesson you want\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <ul class=\"dropdown-menu dropdown-menu-dark\">\r\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"#\">Informatics</a></li>\r\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"#\">Maths</a></li>\r\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"#\">Romanian</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("\r\n");
      out.write("            <ul class=\"navbar-nav ms-auto mb-2 mb-lg-0\">\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link active\" aria-current=\"page\" href=\"#\">En</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link disabled\" aria-current=\"page\" href=\"#\">|</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link active\" aria-current=\"page\" href=\"#\">Ro</a>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("\r\n");
      out.write("            <form class=\"d-flex ms-3\" role=\"search\">\r\n");
      out.write("                <input class=\"form-control me-2\" type=\"search\" placeholder=\"Search\" aria-label=\"Search\">\r\n");
      out.write("                <button class=\"btn btn-success\" type=\"submit\">Search</button>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</nav>\r\n");
      out.write("<div class=\"offcanvas offcanvas-start offcanvas-sidebar\" tabindex=\"-1\" id=\"offcanvasSidebar\" aria-labelledby=\"offcanvasSidebarLabel\">\r\n");
      out.write("    <div class=\"offcanvas-header\">\r\n");
      out.write("        <h5 class=\"offcanvas-title\" id=\"offcanvasSidebarLabel\">Your Settings</h5>\r\n");
      out.write("        <button type=\"button\" class=\"btn-close btn-close-white\" data-bs-dismiss=\"offcanvas\" aria-label=\"Close\"></button>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"offcanvas-body\">\r\n");
      out.write("        <ul class=\"list-group\">\r\n");
      out.write("            <li class=\"list-group-item\">My Profile</li>\r\n");
      out.write("            <li class=\"list-group-item\">Ask a question</li>\r\n");
      out.write("        </ul>\r\n");
      out.write("        <hr>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<a href=\"/admin/posts.html\">viewposts</a>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container content\">\r\n");
      out.write("    <!-- Page header -->\r\n");
      out.write("    <h1 class=\"profile-edit-header\">Edit Profile</h1>\r\n");
      out.write("\r\n");
      out.write("    <!-- Profile Edit Form -->\r\n");
      out.write("    <form class=\"profile-edit-form\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/cms/cmsprofileserv\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("        <input type=\"hidden\" name=\"userId\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.userId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("\r\n");
      out.write("        <div>\r\n");
      out.write("            <label for=\"username\">Username:</label>\r\n");
      out.write("            <input type=\"text\" id=\"username\" name=\"username\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.username}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly />\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div>\r\n");
      out.write("            <label for=\"firstName\">First Name:</label>\r\n");
      out.write("            <input type=\"text\" id=\"firstName\" name=\"firstName\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.firstName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" required />\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div>\r\n");
      out.write("            <label for=\"lastName\">Last Name:</label>\r\n");
      out.write("            <input type=\"text\" id=\"lastName\" name=\"lastName\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.lastName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" required />\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div>\r\n");
      out.write("            <label for=\"email\">Email:</label>\r\n");
      out.write("            <input type=\"email\" id=\"email\" name=\"email\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.email}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" required />\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div>\r\n");
      out.write("            <label for=\"bio\">Bio:</label>\r\n");
      out.write("            <textarea id=\"bio\" name=\"bio\" rows=\"4\" cols=\"50\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.bio}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</textarea>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div>\r\n");
      out.write("            <label for=\"profilePictureUrl\">Profile Picture URL:</label>\r\n");
      out.write("            <input type=\"url\" id=\"profilePictureUrl\" name=\"profilePictureUrl\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.profilePictureUrl}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div>\r\n");
      out.write("            <button type=\"submit\">Update Profile</button>\r\n");
      out.write("            <button type=\"button\" onclick=\"window.location.href='profile.html'\">Cancel</button>\r\n");
      out.write("        </div>\r\n");
      out.write("    </form>\r\n");
      out.write("    <br />\r\n");
      out.write("    <br />\r\n");
      out.write("    <form action=\"cmsprofiledeleteserv\" method=\"post\" onsubmit=\"return confirm('Are you sure you want to delete your account? This action cannot be undone.');\">\r\n");
      out.write("        <button type=\"submit\" style=\"background-color: red; color: white; border: none; padding: 10px 20px; cursor: pointer;\">\r\n");
      out.write("            Delete Account\r\n");
      out.write("        </button>\r\n");
      out.write("    </form>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');
      out.write("<footer class=\"footer\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <p>&copy; 2025 EduMentor. All rights reserved.</p>\r\n");
      out.write("        <p>Today's Date: <span id=\"currentDate\"></span></p>\r\n");
      out.write("    </div>\r\n");
      out.write("</footer>");
      out.write('\r');
      out.write('\n');
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js\" \r\n");
      out.write("        integrity=\"sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r\" \r\n");
      out.write("crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js\" \r\n");
      out.write("        integrity=\"sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy\" \r\n");
      out.write("crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("// Function to format the date as \"Day, Month DD, YYYY\"\r\n");
      out.write("function updateFooterDate() {\r\n");
      out.write("    const options = {weekday: 'long', year: 'numeric', month: 'long', day: 'numeric'};\r\n");
      out.write("    const today = new Date();\r\n");
      out.write("    const formattedDate = today.toLocaleDateString('en-US', options);\r\n");
      out.write("\r\n");
      out.write("    // Set the formatted date in the footer\r\n");
      out.write("    document.getElementById('currentDate').textContent = formattedDate;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("updateFooterDate();\r\n");
      out.write("</script>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
